//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcClient.CoursesDbService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DtoNtu", Namespace="http://schemas.datacontract.org/2004/07/CoursesSearchService")]
    [System.SerializableAttribute()]
    public partial class DtoNtu : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string 課程名稱Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string 班次Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string 授課教師Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string 時間教室Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string 全半年Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string 學分Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string 必選修Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string 總人數Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string 授課對象Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string 選課限制條件Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string 課程網頁Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string 備註Field;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string 課程名稱 {
            get {
                return this.課程名稱Field;
            }
            set {
                if ((object.ReferenceEquals(this.課程名稱Field, value) != true)) {
                    this.課程名稱Field = value;
                    this.RaisePropertyChanged("課程名稱");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public string 班次 {
            get {
                return this.班次Field;
            }
            set {
                if ((object.ReferenceEquals(this.班次Field, value) != true)) {
                    this.班次Field = value;
                    this.RaisePropertyChanged("班次");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string 授課教師 {
            get {
                return this.授課教師Field;
            }
            set {
                if ((object.ReferenceEquals(this.授課教師Field, value) != true)) {
                    this.授課教師Field = value;
                    this.RaisePropertyChanged("授課教師");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string 時間教室 {
            get {
                return this.時間教室Field;
            }
            set {
                if ((object.ReferenceEquals(this.時間教室Field, value) != true)) {
                    this.時間教室Field = value;
                    this.RaisePropertyChanged("時間教室");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public string 全半年 {
            get {
                return this.全半年Field;
            }
            set {
                if ((object.ReferenceEquals(this.全半年Field, value) != true)) {
                    this.全半年Field = value;
                    this.RaisePropertyChanged("全半年");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public string 學分 {
            get {
                return this.學分Field;
            }
            set {
                if ((object.ReferenceEquals(this.學分Field, value) != true)) {
                    this.學分Field = value;
                    this.RaisePropertyChanged("學分");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public string 必選修 {
            get {
                return this.必選修Field;
            }
            set {
                if ((object.ReferenceEquals(this.必選修Field, value) != true)) {
                    this.必選修Field = value;
                    this.RaisePropertyChanged("必選修");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public string 總人數 {
            get {
                return this.總人數Field;
            }
            set {
                if ((object.ReferenceEquals(this.總人數Field, value) != true)) {
                    this.總人數Field = value;
                    this.RaisePropertyChanged("總人數");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public string 授課對象 {
            get {
                return this.授課對象Field;
            }
            set {
                if ((object.ReferenceEquals(this.授課對象Field, value) != true)) {
                    this.授課對象Field = value;
                    this.RaisePropertyChanged("授課對象");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=9)]
        public string 選課限制條件 {
            get {
                return this.選課限制條件Field;
            }
            set {
                if ((object.ReferenceEquals(this.選課限制條件Field, value) != true)) {
                    this.選課限制條件Field = value;
                    this.RaisePropertyChanged("選課限制條件");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=10)]
        public string 課程網頁 {
            get {
                return this.課程網頁Field;
            }
            set {
                if ((object.ReferenceEquals(this.課程網頁Field, value) != true)) {
                    this.課程網頁Field = value;
                    this.RaisePropertyChanged("課程網頁");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=11)]
        public string 備註 {
            get {
                return this.備註Field;
            }
            set {
                if ((object.ReferenceEquals(this.備註Field, value) != true)) {
                    this.備註Field = value;
                    this.RaisePropertyChanged("備註");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DtoSuccess", Namespace="http://schemas.datacontract.org/2004/07/CoursesSearchService")]
    [System.SerializableAttribute()]
    public partial class DtoSuccess : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string 課程名稱Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string 年級Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string 班別Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string 組別Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string 已選課人數Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string 餘額Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string 教師姓名Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string 時間Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string 教室Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string 學分Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string 選必修Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string 系所名稱Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string 限選條件Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string 英語授課Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string 跨領域學分學程Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MoocsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string 業界專家參與Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string 備註Field;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string 課程名稱 {
            get {
                return this.課程名稱Field;
            }
            set {
                if ((object.ReferenceEquals(this.課程名稱Field, value) != true)) {
                    this.課程名稱Field = value;
                    this.RaisePropertyChanged("課程名稱");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public string 年級 {
            get {
                return this.年級Field;
            }
            set {
                if ((object.ReferenceEquals(this.年級Field, value) != true)) {
                    this.年級Field = value;
                    this.RaisePropertyChanged("年級");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string 班別 {
            get {
                return this.班別Field;
            }
            set {
                if ((object.ReferenceEquals(this.班別Field, value) != true)) {
                    this.班別Field = value;
                    this.RaisePropertyChanged("班別");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string 組別 {
            get {
                return this.組別Field;
            }
            set {
                if ((object.ReferenceEquals(this.組別Field, value) != true)) {
                    this.組別Field = value;
                    this.RaisePropertyChanged("組別");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public string 已選課人數 {
            get {
                return this.已選課人數Field;
            }
            set {
                if ((object.ReferenceEquals(this.已選課人數Field, value) != true)) {
                    this.已選課人數Field = value;
                    this.RaisePropertyChanged("已選課人數");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public string 餘額 {
            get {
                return this.餘額Field;
            }
            set {
                if ((object.ReferenceEquals(this.餘額Field, value) != true)) {
                    this.餘額Field = value;
                    this.RaisePropertyChanged("餘額");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public string 教師姓名 {
            get {
                return this.教師姓名Field;
            }
            set {
                if ((object.ReferenceEquals(this.教師姓名Field, value) != true)) {
                    this.教師姓名Field = value;
                    this.RaisePropertyChanged("教師姓名");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public string 時間 {
            get {
                return this.時間Field;
            }
            set {
                if ((object.ReferenceEquals(this.時間Field, value) != true)) {
                    this.時間Field = value;
                    this.RaisePropertyChanged("時間");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public string 教室 {
            get {
                return this.教室Field;
            }
            set {
                if ((object.ReferenceEquals(this.教室Field, value) != true)) {
                    this.教室Field = value;
                    this.RaisePropertyChanged("教室");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=9)]
        public string 學分 {
            get {
                return this.學分Field;
            }
            set {
                if ((object.ReferenceEquals(this.學分Field, value) != true)) {
                    this.學分Field = value;
                    this.RaisePropertyChanged("學分");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=10)]
        public string 選必修 {
            get {
                return this.選必修Field;
            }
            set {
                if ((object.ReferenceEquals(this.選必修Field, value) != true)) {
                    this.選必修Field = value;
                    this.RaisePropertyChanged("選必修");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=11)]
        public string 系所名稱 {
            get {
                return this.系所名稱Field;
            }
            set {
                if ((object.ReferenceEquals(this.系所名稱Field, value) != true)) {
                    this.系所名稱Field = value;
                    this.RaisePropertyChanged("系所名稱");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=12)]
        public string 限選條件 {
            get {
                return this.限選條件Field;
            }
            set {
                if ((object.ReferenceEquals(this.限選條件Field, value) != true)) {
                    this.限選條件Field = value;
                    this.RaisePropertyChanged("限選條件");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=13)]
        public string 英語授課 {
            get {
                return this.英語授課Field;
            }
            set {
                if ((object.ReferenceEquals(this.英語授課Field, value) != true)) {
                    this.英語授課Field = value;
                    this.RaisePropertyChanged("英語授課");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=14)]
        public string 跨領域學分學程 {
            get {
                return this.跨領域學分學程Field;
            }
            set {
                if ((object.ReferenceEquals(this.跨領域學分學程Field, value) != true)) {
                    this.跨領域學分學程Field = value;
                    this.RaisePropertyChanged("跨領域學分學程");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=15)]
        public string Moocs {
            get {
                return this.MoocsField;
            }
            set {
                if ((object.ReferenceEquals(this.MoocsField, value) != true)) {
                    this.MoocsField = value;
                    this.RaisePropertyChanged("Moocs");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=16)]
        public string 業界專家參與 {
            get {
                return this.業界專家參與Field;
            }
            set {
                if ((object.ReferenceEquals(this.業界專家參與Field, value) != true)) {
                    this.業界專家參與Field = value;
                    this.RaisePropertyChanged("業界專家參與");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=17)]
        public string 備註 {
            get {
                return this.備註Field;
            }
            set {
                if ((object.ReferenceEquals(this.備註Field, value) != true)) {
                    this.備註Field = value;
                    this.RaisePropertyChanged("備註");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CoursesDbService.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetNtuCourses", ReplyAction="http://tempuri.org/IService1/GetNtuCoursesResponse")]
        MvcClient.CoursesDbService.DtoNtu[] GetNtuCourses();
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/GetNtuCourses", ReplyAction="http://tempuri.org/IService1/GetNtuCoursesResponse")]
        System.IAsyncResult BeginGetNtuCourses(System.AsyncCallback callback, object asyncState);
        
        MvcClient.CoursesDbService.DtoNtu[] EndGetNtuCourses(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetNtuCoursesBySearchAll", ReplyAction="http://tempuri.org/IService1/GetNtuCoursesBySearchAllResponse")]
        MvcClient.CoursesDbService.DtoNtu[] GetNtuCoursesBySearchAll(string query);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/GetNtuCoursesBySearchAll", ReplyAction="http://tempuri.org/IService1/GetNtuCoursesBySearchAllResponse")]
        System.IAsyncResult BeginGetNtuCoursesBySearchAll(string query, System.AsyncCallback callback, object asyncState);
        
        MvcClient.CoursesDbService.DtoNtu[] EndGetNtuCoursesBySearchAll(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetNtuCoursesByCourseName", ReplyAction="http://tempuri.org/IService1/GetNtuCoursesByCourseNameResponse")]
        MvcClient.CoursesDbService.DtoNtu[] GetNtuCoursesByCourseName(string query);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/GetNtuCoursesByCourseName", ReplyAction="http://tempuri.org/IService1/GetNtuCoursesByCourseNameResponse")]
        System.IAsyncResult BeginGetNtuCoursesByCourseName(string query, System.AsyncCallback callback, object asyncState);
        
        MvcClient.CoursesDbService.DtoNtu[] EndGetNtuCoursesByCourseName(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetNtuCoursesByTeacher", ReplyAction="http://tempuri.org/IService1/GetNtuCoursesByTeacherResponse")]
        MvcClient.CoursesDbService.DtoNtu[] GetNtuCoursesByTeacher(string query);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/GetNtuCoursesByTeacher", ReplyAction="http://tempuri.org/IService1/GetNtuCoursesByTeacherResponse")]
        System.IAsyncResult BeginGetNtuCoursesByTeacher(string query, System.AsyncCallback callback, object asyncState);
        
        MvcClient.CoursesDbService.DtoNtu[] EndGetNtuCoursesByTeacher(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetNtuCoursesByWeekday", ReplyAction="http://tempuri.org/IService1/GetNtuCoursesByWeekdayResponse")]
        MvcClient.CoursesDbService.DtoNtu[] GetNtuCoursesByWeekday(string Weekday);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/GetNtuCoursesByWeekday", ReplyAction="http://tempuri.org/IService1/GetNtuCoursesByWeekdayResponse")]
        System.IAsyncResult BeginGetNtuCoursesByWeekday(string Weekday, System.AsyncCallback callback, object asyncState);
        
        MvcClient.CoursesDbService.DtoNtu[] EndGetNtuCoursesByWeekday(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetNtuCoursesBySearchDepartment", ReplyAction="http://tempuri.org/IService1/GetNtuCoursesBySearchDepartmentResponse")]
        MvcClient.CoursesDbService.DtoNtu[] GetNtuCoursesBySearchDepartment(string query);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/GetNtuCoursesBySearchDepartment", ReplyAction="http://tempuri.org/IService1/GetNtuCoursesBySearchDepartmentResponse")]
        System.IAsyncResult BeginGetNtuCoursesBySearchDepartment(string query, System.AsyncCallback callback, object asyncState);
        
        MvcClient.CoursesDbService.DtoNtu[] EndGetNtuCoursesBySearchDepartment(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetSuccessCourses", ReplyAction="http://tempuri.org/IService1/GetSuccessCoursesResponse")]
        MvcClient.CoursesDbService.DtoSuccess[] GetSuccessCourses();
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/GetSuccessCourses", ReplyAction="http://tempuri.org/IService1/GetSuccessCoursesResponse")]
        System.IAsyncResult BeginGetSuccessCourses(System.AsyncCallback callback, object asyncState);
        
        MvcClient.CoursesDbService.DtoSuccess[] EndGetSuccessCourses(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetSuccessCoursesBySearchAll", ReplyAction="http://tempuri.org/IService1/GetSuccessCoursesBySearchAllResponse")]
        MvcClient.CoursesDbService.DtoSuccess[] GetSuccessCoursesBySearchAll(string query);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/GetSuccessCoursesBySearchAll", ReplyAction="http://tempuri.org/IService1/GetSuccessCoursesBySearchAllResponse")]
        System.IAsyncResult BeginGetSuccessCoursesBySearchAll(string query, System.AsyncCallback callback, object asyncState);
        
        MvcClient.CoursesDbService.DtoSuccess[] EndGetSuccessCoursesBySearchAll(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetSuccessCoursesByCourseName", ReplyAction="http://tempuri.org/IService1/GetSuccessCoursesByCourseNameResponse")]
        MvcClient.CoursesDbService.DtoSuccess[] GetSuccessCoursesByCourseName(string query);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/GetSuccessCoursesByCourseName", ReplyAction="http://tempuri.org/IService1/GetSuccessCoursesByCourseNameResponse")]
        System.IAsyncResult BeginGetSuccessCoursesByCourseName(string query, System.AsyncCallback callback, object asyncState);
        
        MvcClient.CoursesDbService.DtoSuccess[] EndGetSuccessCoursesByCourseName(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetSuccessCoursesByTeacher", ReplyAction="http://tempuri.org/IService1/GetSuccessCoursesByTeacherResponse")]
        MvcClient.CoursesDbService.DtoSuccess[] GetSuccessCoursesByTeacher(string query);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/GetSuccessCoursesByTeacher", ReplyAction="http://tempuri.org/IService1/GetSuccessCoursesByTeacherResponse")]
        System.IAsyncResult BeginGetSuccessCoursesByTeacher(string query, System.AsyncCallback callback, object asyncState);
        
        MvcClient.CoursesDbService.DtoSuccess[] EndGetSuccessCoursesByTeacher(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetSuccessCoursesByWeekday", ReplyAction="http://tempuri.org/IService1/GetSuccessCoursesByWeekdayResponse")]
        MvcClient.CoursesDbService.DtoSuccess[] GetSuccessCoursesByWeekday(string Weekday);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/GetSuccessCoursesByWeekday", ReplyAction="http://tempuri.org/IService1/GetSuccessCoursesByWeekdayResponse")]
        System.IAsyncResult BeginGetSuccessCoursesByWeekday(string Weekday, System.AsyncCallback callback, object asyncState);
        
        MvcClient.CoursesDbService.DtoSuccess[] EndGetSuccessCoursesByWeekday(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetSuccessCoursesBySearchDepartment", ReplyAction="http://tempuri.org/IService1/GetSuccessCoursesBySearchDepartmentResponse")]
        MvcClient.CoursesDbService.DtoSuccess[] GetSuccessCoursesBySearchDepartment(string query);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/GetSuccessCoursesBySearchDepartment", ReplyAction="http://tempuri.org/IService1/GetSuccessCoursesBySearchDepartmentResponse")]
        System.IAsyncResult BeginGetSuccessCoursesBySearchDepartment(string query, System.AsyncCallback callback, object asyncState);
        
        MvcClient.CoursesDbService.DtoSuccess[] EndGetSuccessCoursesBySearchDepartment(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : MvcClient.CoursesDbService.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetNtuCoursesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetNtuCoursesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public MvcClient.CoursesDbService.DtoNtu[] Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((MvcClient.CoursesDbService.DtoNtu[])(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetNtuCoursesBySearchAllCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetNtuCoursesBySearchAllCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public MvcClient.CoursesDbService.DtoNtu[] Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((MvcClient.CoursesDbService.DtoNtu[])(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetNtuCoursesByCourseNameCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetNtuCoursesByCourseNameCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public MvcClient.CoursesDbService.DtoNtu[] Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((MvcClient.CoursesDbService.DtoNtu[])(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetNtuCoursesByTeacherCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetNtuCoursesByTeacherCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public MvcClient.CoursesDbService.DtoNtu[] Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((MvcClient.CoursesDbService.DtoNtu[])(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetNtuCoursesByWeekdayCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetNtuCoursesByWeekdayCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public MvcClient.CoursesDbService.DtoNtu[] Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((MvcClient.CoursesDbService.DtoNtu[])(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetNtuCoursesBySearchDepartmentCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetNtuCoursesBySearchDepartmentCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public MvcClient.CoursesDbService.DtoNtu[] Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((MvcClient.CoursesDbService.DtoNtu[])(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetSuccessCoursesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetSuccessCoursesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public MvcClient.CoursesDbService.DtoSuccess[] Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((MvcClient.CoursesDbService.DtoSuccess[])(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetSuccessCoursesBySearchAllCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetSuccessCoursesBySearchAllCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public MvcClient.CoursesDbService.DtoSuccess[] Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((MvcClient.CoursesDbService.DtoSuccess[])(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetSuccessCoursesByCourseNameCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetSuccessCoursesByCourseNameCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public MvcClient.CoursesDbService.DtoSuccess[] Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((MvcClient.CoursesDbService.DtoSuccess[])(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetSuccessCoursesByTeacherCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetSuccessCoursesByTeacherCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public MvcClient.CoursesDbService.DtoSuccess[] Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((MvcClient.CoursesDbService.DtoSuccess[])(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetSuccessCoursesByWeekdayCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetSuccessCoursesByWeekdayCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public MvcClient.CoursesDbService.DtoSuccess[] Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((MvcClient.CoursesDbService.DtoSuccess[])(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetSuccessCoursesBySearchDepartmentCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetSuccessCoursesBySearchDepartmentCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public MvcClient.CoursesDbService.DtoSuccess[] Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((MvcClient.CoursesDbService.DtoSuccess[])(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<MvcClient.CoursesDbService.IService1>, MvcClient.CoursesDbService.IService1 {
        
        private BeginOperationDelegate onBeginGetNtuCoursesDelegate;
        
        private EndOperationDelegate onEndGetNtuCoursesDelegate;
        
        private System.Threading.SendOrPostCallback onGetNtuCoursesCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetNtuCoursesBySearchAllDelegate;
        
        private EndOperationDelegate onEndGetNtuCoursesBySearchAllDelegate;
        
        private System.Threading.SendOrPostCallback onGetNtuCoursesBySearchAllCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetNtuCoursesByCourseNameDelegate;
        
        private EndOperationDelegate onEndGetNtuCoursesByCourseNameDelegate;
        
        private System.Threading.SendOrPostCallback onGetNtuCoursesByCourseNameCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetNtuCoursesByTeacherDelegate;
        
        private EndOperationDelegate onEndGetNtuCoursesByTeacherDelegate;
        
        private System.Threading.SendOrPostCallback onGetNtuCoursesByTeacherCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetNtuCoursesByWeekdayDelegate;
        
        private EndOperationDelegate onEndGetNtuCoursesByWeekdayDelegate;
        
        private System.Threading.SendOrPostCallback onGetNtuCoursesByWeekdayCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetNtuCoursesBySearchDepartmentDelegate;
        
        private EndOperationDelegate onEndGetNtuCoursesBySearchDepartmentDelegate;
        
        private System.Threading.SendOrPostCallback onGetNtuCoursesBySearchDepartmentCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetSuccessCoursesDelegate;
        
        private EndOperationDelegate onEndGetSuccessCoursesDelegate;
        
        private System.Threading.SendOrPostCallback onGetSuccessCoursesCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetSuccessCoursesBySearchAllDelegate;
        
        private EndOperationDelegate onEndGetSuccessCoursesBySearchAllDelegate;
        
        private System.Threading.SendOrPostCallback onGetSuccessCoursesBySearchAllCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetSuccessCoursesByCourseNameDelegate;
        
        private EndOperationDelegate onEndGetSuccessCoursesByCourseNameDelegate;
        
        private System.Threading.SendOrPostCallback onGetSuccessCoursesByCourseNameCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetSuccessCoursesByTeacherDelegate;
        
        private EndOperationDelegate onEndGetSuccessCoursesByTeacherDelegate;
        
        private System.Threading.SendOrPostCallback onGetSuccessCoursesByTeacherCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetSuccessCoursesByWeekdayDelegate;
        
        private EndOperationDelegate onEndGetSuccessCoursesByWeekdayDelegate;
        
        private System.Threading.SendOrPostCallback onGetSuccessCoursesByWeekdayCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetSuccessCoursesBySearchDepartmentDelegate;
        
        private EndOperationDelegate onEndGetSuccessCoursesBySearchDepartmentDelegate;
        
        private System.Threading.SendOrPostCallback onGetSuccessCoursesBySearchDepartmentCompletedDelegate;
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public event System.EventHandler<GetNtuCoursesCompletedEventArgs> GetNtuCoursesCompleted;
        
        public event System.EventHandler<GetNtuCoursesBySearchAllCompletedEventArgs> GetNtuCoursesBySearchAllCompleted;
        
        public event System.EventHandler<GetNtuCoursesByCourseNameCompletedEventArgs> GetNtuCoursesByCourseNameCompleted;
        
        public event System.EventHandler<GetNtuCoursesByTeacherCompletedEventArgs> GetNtuCoursesByTeacherCompleted;
        
        public event System.EventHandler<GetNtuCoursesByWeekdayCompletedEventArgs> GetNtuCoursesByWeekdayCompleted;
        
        public event System.EventHandler<GetNtuCoursesBySearchDepartmentCompletedEventArgs> GetNtuCoursesBySearchDepartmentCompleted;
        
        public event System.EventHandler<GetSuccessCoursesCompletedEventArgs> GetSuccessCoursesCompleted;
        
        public event System.EventHandler<GetSuccessCoursesBySearchAllCompletedEventArgs> GetSuccessCoursesBySearchAllCompleted;
        
        public event System.EventHandler<GetSuccessCoursesByCourseNameCompletedEventArgs> GetSuccessCoursesByCourseNameCompleted;
        
        public event System.EventHandler<GetSuccessCoursesByTeacherCompletedEventArgs> GetSuccessCoursesByTeacherCompleted;
        
        public event System.EventHandler<GetSuccessCoursesByWeekdayCompletedEventArgs> GetSuccessCoursesByWeekdayCompleted;
        
        public event System.EventHandler<GetSuccessCoursesBySearchDepartmentCompletedEventArgs> GetSuccessCoursesBySearchDepartmentCompleted;
        
        public MvcClient.CoursesDbService.DtoNtu[] GetNtuCourses() {
            return base.Channel.GetNtuCourses();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginGetNtuCourses(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetNtuCourses(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public MvcClient.CoursesDbService.DtoNtu[] EndGetNtuCourses(System.IAsyncResult result) {
            return base.Channel.EndGetNtuCourses(result);
        }
        
        private System.IAsyncResult OnBeginGetNtuCourses(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return this.BeginGetNtuCourses(callback, asyncState);
        }
        
        private object[] OnEndGetNtuCourses(System.IAsyncResult result) {
            MvcClient.CoursesDbService.DtoNtu[] retVal = this.EndGetNtuCourses(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetNtuCoursesCompleted(object state) {
            if ((this.GetNtuCoursesCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetNtuCoursesCompleted(this, new GetNtuCoursesCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetNtuCoursesAsync() {
            this.GetNtuCoursesAsync(null);
        }
        
        public void GetNtuCoursesAsync(object userState) {
            if ((this.onBeginGetNtuCoursesDelegate == null)) {
                this.onBeginGetNtuCoursesDelegate = new BeginOperationDelegate(this.OnBeginGetNtuCourses);
            }
            if ((this.onEndGetNtuCoursesDelegate == null)) {
                this.onEndGetNtuCoursesDelegate = new EndOperationDelegate(this.OnEndGetNtuCourses);
            }
            if ((this.onGetNtuCoursesCompletedDelegate == null)) {
                this.onGetNtuCoursesCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetNtuCoursesCompleted);
            }
            base.InvokeAsync(this.onBeginGetNtuCoursesDelegate, null, this.onEndGetNtuCoursesDelegate, this.onGetNtuCoursesCompletedDelegate, userState);
        }
        
        public MvcClient.CoursesDbService.DtoNtu[] GetNtuCoursesBySearchAll(string query) {
            return base.Channel.GetNtuCoursesBySearchAll(query);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginGetNtuCoursesBySearchAll(string query, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetNtuCoursesBySearchAll(query, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public MvcClient.CoursesDbService.DtoNtu[] EndGetNtuCoursesBySearchAll(System.IAsyncResult result) {
            return base.Channel.EndGetNtuCoursesBySearchAll(result);
        }
        
        private System.IAsyncResult OnBeginGetNtuCoursesBySearchAll(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string query = ((string)(inValues[0]));
            return this.BeginGetNtuCoursesBySearchAll(query, callback, asyncState);
        }
        
        private object[] OnEndGetNtuCoursesBySearchAll(System.IAsyncResult result) {
            MvcClient.CoursesDbService.DtoNtu[] retVal = this.EndGetNtuCoursesBySearchAll(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetNtuCoursesBySearchAllCompleted(object state) {
            if ((this.GetNtuCoursesBySearchAllCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetNtuCoursesBySearchAllCompleted(this, new GetNtuCoursesBySearchAllCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetNtuCoursesBySearchAllAsync(string query) {
            this.GetNtuCoursesBySearchAllAsync(query, null);
        }
        
        public void GetNtuCoursesBySearchAllAsync(string query, object userState) {
            if ((this.onBeginGetNtuCoursesBySearchAllDelegate == null)) {
                this.onBeginGetNtuCoursesBySearchAllDelegate = new BeginOperationDelegate(this.OnBeginGetNtuCoursesBySearchAll);
            }
            if ((this.onEndGetNtuCoursesBySearchAllDelegate == null)) {
                this.onEndGetNtuCoursesBySearchAllDelegate = new EndOperationDelegate(this.OnEndGetNtuCoursesBySearchAll);
            }
            if ((this.onGetNtuCoursesBySearchAllCompletedDelegate == null)) {
                this.onGetNtuCoursesBySearchAllCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetNtuCoursesBySearchAllCompleted);
            }
            base.InvokeAsync(this.onBeginGetNtuCoursesBySearchAllDelegate, new object[] {
                        query}, this.onEndGetNtuCoursesBySearchAllDelegate, this.onGetNtuCoursesBySearchAllCompletedDelegate, userState);
        }
        
        public MvcClient.CoursesDbService.DtoNtu[] GetNtuCoursesByCourseName(string query) {
            return base.Channel.GetNtuCoursesByCourseName(query);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginGetNtuCoursesByCourseName(string query, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetNtuCoursesByCourseName(query, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public MvcClient.CoursesDbService.DtoNtu[] EndGetNtuCoursesByCourseName(System.IAsyncResult result) {
            return base.Channel.EndGetNtuCoursesByCourseName(result);
        }
        
        private System.IAsyncResult OnBeginGetNtuCoursesByCourseName(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string query = ((string)(inValues[0]));
            return this.BeginGetNtuCoursesByCourseName(query, callback, asyncState);
        }
        
        private object[] OnEndGetNtuCoursesByCourseName(System.IAsyncResult result) {
            MvcClient.CoursesDbService.DtoNtu[] retVal = this.EndGetNtuCoursesByCourseName(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetNtuCoursesByCourseNameCompleted(object state) {
            if ((this.GetNtuCoursesByCourseNameCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetNtuCoursesByCourseNameCompleted(this, new GetNtuCoursesByCourseNameCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetNtuCoursesByCourseNameAsync(string query) {
            this.GetNtuCoursesByCourseNameAsync(query, null);
        }
        
        public void GetNtuCoursesByCourseNameAsync(string query, object userState) {
            if ((this.onBeginGetNtuCoursesByCourseNameDelegate == null)) {
                this.onBeginGetNtuCoursesByCourseNameDelegate = new BeginOperationDelegate(this.OnBeginGetNtuCoursesByCourseName);
            }
            if ((this.onEndGetNtuCoursesByCourseNameDelegate == null)) {
                this.onEndGetNtuCoursesByCourseNameDelegate = new EndOperationDelegate(this.OnEndGetNtuCoursesByCourseName);
            }
            if ((this.onGetNtuCoursesByCourseNameCompletedDelegate == null)) {
                this.onGetNtuCoursesByCourseNameCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetNtuCoursesByCourseNameCompleted);
            }
            base.InvokeAsync(this.onBeginGetNtuCoursesByCourseNameDelegate, new object[] {
                        query}, this.onEndGetNtuCoursesByCourseNameDelegate, this.onGetNtuCoursesByCourseNameCompletedDelegate, userState);
        }
        
        public MvcClient.CoursesDbService.DtoNtu[] GetNtuCoursesByTeacher(string query) {
            return base.Channel.GetNtuCoursesByTeacher(query);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginGetNtuCoursesByTeacher(string query, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetNtuCoursesByTeacher(query, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public MvcClient.CoursesDbService.DtoNtu[] EndGetNtuCoursesByTeacher(System.IAsyncResult result) {
            return base.Channel.EndGetNtuCoursesByTeacher(result);
        }
        
        private System.IAsyncResult OnBeginGetNtuCoursesByTeacher(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string query = ((string)(inValues[0]));
            return this.BeginGetNtuCoursesByTeacher(query, callback, asyncState);
        }
        
        private object[] OnEndGetNtuCoursesByTeacher(System.IAsyncResult result) {
            MvcClient.CoursesDbService.DtoNtu[] retVal = this.EndGetNtuCoursesByTeacher(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetNtuCoursesByTeacherCompleted(object state) {
            if ((this.GetNtuCoursesByTeacherCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetNtuCoursesByTeacherCompleted(this, new GetNtuCoursesByTeacherCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetNtuCoursesByTeacherAsync(string query) {
            this.GetNtuCoursesByTeacherAsync(query, null);
        }
        
        public void GetNtuCoursesByTeacherAsync(string query, object userState) {
            if ((this.onBeginGetNtuCoursesByTeacherDelegate == null)) {
                this.onBeginGetNtuCoursesByTeacherDelegate = new BeginOperationDelegate(this.OnBeginGetNtuCoursesByTeacher);
            }
            if ((this.onEndGetNtuCoursesByTeacherDelegate == null)) {
                this.onEndGetNtuCoursesByTeacherDelegate = new EndOperationDelegate(this.OnEndGetNtuCoursesByTeacher);
            }
            if ((this.onGetNtuCoursesByTeacherCompletedDelegate == null)) {
                this.onGetNtuCoursesByTeacherCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetNtuCoursesByTeacherCompleted);
            }
            base.InvokeAsync(this.onBeginGetNtuCoursesByTeacherDelegate, new object[] {
                        query}, this.onEndGetNtuCoursesByTeacherDelegate, this.onGetNtuCoursesByTeacherCompletedDelegate, userState);
        }
        
        public MvcClient.CoursesDbService.DtoNtu[] GetNtuCoursesByWeekday(string Weekday) {
            return base.Channel.GetNtuCoursesByWeekday(Weekday);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginGetNtuCoursesByWeekday(string Weekday, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetNtuCoursesByWeekday(Weekday, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public MvcClient.CoursesDbService.DtoNtu[] EndGetNtuCoursesByWeekday(System.IAsyncResult result) {
            return base.Channel.EndGetNtuCoursesByWeekday(result);
        }
        
        private System.IAsyncResult OnBeginGetNtuCoursesByWeekday(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string Weekday = ((string)(inValues[0]));
            return this.BeginGetNtuCoursesByWeekday(Weekday, callback, asyncState);
        }
        
        private object[] OnEndGetNtuCoursesByWeekday(System.IAsyncResult result) {
            MvcClient.CoursesDbService.DtoNtu[] retVal = this.EndGetNtuCoursesByWeekday(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetNtuCoursesByWeekdayCompleted(object state) {
            if ((this.GetNtuCoursesByWeekdayCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetNtuCoursesByWeekdayCompleted(this, new GetNtuCoursesByWeekdayCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetNtuCoursesByWeekdayAsync(string Weekday) {
            this.GetNtuCoursesByWeekdayAsync(Weekday, null);
        }
        
        public void GetNtuCoursesByWeekdayAsync(string Weekday, object userState) {
            if ((this.onBeginGetNtuCoursesByWeekdayDelegate == null)) {
                this.onBeginGetNtuCoursesByWeekdayDelegate = new BeginOperationDelegate(this.OnBeginGetNtuCoursesByWeekday);
            }
            if ((this.onEndGetNtuCoursesByWeekdayDelegate == null)) {
                this.onEndGetNtuCoursesByWeekdayDelegate = new EndOperationDelegate(this.OnEndGetNtuCoursesByWeekday);
            }
            if ((this.onGetNtuCoursesByWeekdayCompletedDelegate == null)) {
                this.onGetNtuCoursesByWeekdayCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetNtuCoursesByWeekdayCompleted);
            }
            base.InvokeAsync(this.onBeginGetNtuCoursesByWeekdayDelegate, new object[] {
                        Weekday}, this.onEndGetNtuCoursesByWeekdayDelegate, this.onGetNtuCoursesByWeekdayCompletedDelegate, userState);
        }
        
        public MvcClient.CoursesDbService.DtoNtu[] GetNtuCoursesBySearchDepartment(string query) {
            return base.Channel.GetNtuCoursesBySearchDepartment(query);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginGetNtuCoursesBySearchDepartment(string query, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetNtuCoursesBySearchDepartment(query, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public MvcClient.CoursesDbService.DtoNtu[] EndGetNtuCoursesBySearchDepartment(System.IAsyncResult result) {
            return base.Channel.EndGetNtuCoursesBySearchDepartment(result);
        }
        
        private System.IAsyncResult OnBeginGetNtuCoursesBySearchDepartment(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string query = ((string)(inValues[0]));
            return this.BeginGetNtuCoursesBySearchDepartment(query, callback, asyncState);
        }
        
        private object[] OnEndGetNtuCoursesBySearchDepartment(System.IAsyncResult result) {
            MvcClient.CoursesDbService.DtoNtu[] retVal = this.EndGetNtuCoursesBySearchDepartment(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetNtuCoursesBySearchDepartmentCompleted(object state) {
            if ((this.GetNtuCoursesBySearchDepartmentCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetNtuCoursesBySearchDepartmentCompleted(this, new GetNtuCoursesBySearchDepartmentCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetNtuCoursesBySearchDepartmentAsync(string query) {
            this.GetNtuCoursesBySearchDepartmentAsync(query, null);
        }
        
        public void GetNtuCoursesBySearchDepartmentAsync(string query, object userState) {
            if ((this.onBeginGetNtuCoursesBySearchDepartmentDelegate == null)) {
                this.onBeginGetNtuCoursesBySearchDepartmentDelegate = new BeginOperationDelegate(this.OnBeginGetNtuCoursesBySearchDepartment);
            }
            if ((this.onEndGetNtuCoursesBySearchDepartmentDelegate == null)) {
                this.onEndGetNtuCoursesBySearchDepartmentDelegate = new EndOperationDelegate(this.OnEndGetNtuCoursesBySearchDepartment);
            }
            if ((this.onGetNtuCoursesBySearchDepartmentCompletedDelegate == null)) {
                this.onGetNtuCoursesBySearchDepartmentCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetNtuCoursesBySearchDepartmentCompleted);
            }
            base.InvokeAsync(this.onBeginGetNtuCoursesBySearchDepartmentDelegate, new object[] {
                        query}, this.onEndGetNtuCoursesBySearchDepartmentDelegate, this.onGetNtuCoursesBySearchDepartmentCompletedDelegate, userState);
        }
        
        public MvcClient.CoursesDbService.DtoSuccess[] GetSuccessCourses() {
            return base.Channel.GetSuccessCourses();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginGetSuccessCourses(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetSuccessCourses(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public MvcClient.CoursesDbService.DtoSuccess[] EndGetSuccessCourses(System.IAsyncResult result) {
            return base.Channel.EndGetSuccessCourses(result);
        }
        
        private System.IAsyncResult OnBeginGetSuccessCourses(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return this.BeginGetSuccessCourses(callback, asyncState);
        }
        
        private object[] OnEndGetSuccessCourses(System.IAsyncResult result) {
            MvcClient.CoursesDbService.DtoSuccess[] retVal = this.EndGetSuccessCourses(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetSuccessCoursesCompleted(object state) {
            if ((this.GetSuccessCoursesCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetSuccessCoursesCompleted(this, new GetSuccessCoursesCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetSuccessCoursesAsync() {
            this.GetSuccessCoursesAsync(null);
        }
        
        public void GetSuccessCoursesAsync(object userState) {
            if ((this.onBeginGetSuccessCoursesDelegate == null)) {
                this.onBeginGetSuccessCoursesDelegate = new BeginOperationDelegate(this.OnBeginGetSuccessCourses);
            }
            if ((this.onEndGetSuccessCoursesDelegate == null)) {
                this.onEndGetSuccessCoursesDelegate = new EndOperationDelegate(this.OnEndGetSuccessCourses);
            }
            if ((this.onGetSuccessCoursesCompletedDelegate == null)) {
                this.onGetSuccessCoursesCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetSuccessCoursesCompleted);
            }
            base.InvokeAsync(this.onBeginGetSuccessCoursesDelegate, null, this.onEndGetSuccessCoursesDelegate, this.onGetSuccessCoursesCompletedDelegate, userState);
        }
        
        public MvcClient.CoursesDbService.DtoSuccess[] GetSuccessCoursesBySearchAll(string query) {
            return base.Channel.GetSuccessCoursesBySearchAll(query);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginGetSuccessCoursesBySearchAll(string query, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetSuccessCoursesBySearchAll(query, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public MvcClient.CoursesDbService.DtoSuccess[] EndGetSuccessCoursesBySearchAll(System.IAsyncResult result) {
            return base.Channel.EndGetSuccessCoursesBySearchAll(result);
        }
        
        private System.IAsyncResult OnBeginGetSuccessCoursesBySearchAll(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string query = ((string)(inValues[0]));
            return this.BeginGetSuccessCoursesBySearchAll(query, callback, asyncState);
        }
        
        private object[] OnEndGetSuccessCoursesBySearchAll(System.IAsyncResult result) {
            MvcClient.CoursesDbService.DtoSuccess[] retVal = this.EndGetSuccessCoursesBySearchAll(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetSuccessCoursesBySearchAllCompleted(object state) {
            if ((this.GetSuccessCoursesBySearchAllCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetSuccessCoursesBySearchAllCompleted(this, new GetSuccessCoursesBySearchAllCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetSuccessCoursesBySearchAllAsync(string query) {
            this.GetSuccessCoursesBySearchAllAsync(query, null);
        }
        
        public void GetSuccessCoursesBySearchAllAsync(string query, object userState) {
            if ((this.onBeginGetSuccessCoursesBySearchAllDelegate == null)) {
                this.onBeginGetSuccessCoursesBySearchAllDelegate = new BeginOperationDelegate(this.OnBeginGetSuccessCoursesBySearchAll);
            }
            if ((this.onEndGetSuccessCoursesBySearchAllDelegate == null)) {
                this.onEndGetSuccessCoursesBySearchAllDelegate = new EndOperationDelegate(this.OnEndGetSuccessCoursesBySearchAll);
            }
            if ((this.onGetSuccessCoursesBySearchAllCompletedDelegate == null)) {
                this.onGetSuccessCoursesBySearchAllCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetSuccessCoursesBySearchAllCompleted);
            }
            base.InvokeAsync(this.onBeginGetSuccessCoursesBySearchAllDelegate, new object[] {
                        query}, this.onEndGetSuccessCoursesBySearchAllDelegate, this.onGetSuccessCoursesBySearchAllCompletedDelegate, userState);
        }
        
        public MvcClient.CoursesDbService.DtoSuccess[] GetSuccessCoursesByCourseName(string query) {
            return base.Channel.GetSuccessCoursesByCourseName(query);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginGetSuccessCoursesByCourseName(string query, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetSuccessCoursesByCourseName(query, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public MvcClient.CoursesDbService.DtoSuccess[] EndGetSuccessCoursesByCourseName(System.IAsyncResult result) {
            return base.Channel.EndGetSuccessCoursesByCourseName(result);
        }
        
        private System.IAsyncResult OnBeginGetSuccessCoursesByCourseName(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string query = ((string)(inValues[0]));
            return this.BeginGetSuccessCoursesByCourseName(query, callback, asyncState);
        }
        
        private object[] OnEndGetSuccessCoursesByCourseName(System.IAsyncResult result) {
            MvcClient.CoursesDbService.DtoSuccess[] retVal = this.EndGetSuccessCoursesByCourseName(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetSuccessCoursesByCourseNameCompleted(object state) {
            if ((this.GetSuccessCoursesByCourseNameCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetSuccessCoursesByCourseNameCompleted(this, new GetSuccessCoursesByCourseNameCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetSuccessCoursesByCourseNameAsync(string query) {
            this.GetSuccessCoursesByCourseNameAsync(query, null);
        }
        
        public void GetSuccessCoursesByCourseNameAsync(string query, object userState) {
            if ((this.onBeginGetSuccessCoursesByCourseNameDelegate == null)) {
                this.onBeginGetSuccessCoursesByCourseNameDelegate = new BeginOperationDelegate(this.OnBeginGetSuccessCoursesByCourseName);
            }
            if ((this.onEndGetSuccessCoursesByCourseNameDelegate == null)) {
                this.onEndGetSuccessCoursesByCourseNameDelegate = new EndOperationDelegate(this.OnEndGetSuccessCoursesByCourseName);
            }
            if ((this.onGetSuccessCoursesByCourseNameCompletedDelegate == null)) {
                this.onGetSuccessCoursesByCourseNameCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetSuccessCoursesByCourseNameCompleted);
            }
            base.InvokeAsync(this.onBeginGetSuccessCoursesByCourseNameDelegate, new object[] {
                        query}, this.onEndGetSuccessCoursesByCourseNameDelegate, this.onGetSuccessCoursesByCourseNameCompletedDelegate, userState);
        }
        
        public MvcClient.CoursesDbService.DtoSuccess[] GetSuccessCoursesByTeacher(string query) {
            return base.Channel.GetSuccessCoursesByTeacher(query);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginGetSuccessCoursesByTeacher(string query, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetSuccessCoursesByTeacher(query, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public MvcClient.CoursesDbService.DtoSuccess[] EndGetSuccessCoursesByTeacher(System.IAsyncResult result) {
            return base.Channel.EndGetSuccessCoursesByTeacher(result);
        }
        
        private System.IAsyncResult OnBeginGetSuccessCoursesByTeacher(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string query = ((string)(inValues[0]));
            return this.BeginGetSuccessCoursesByTeacher(query, callback, asyncState);
        }
        
        private object[] OnEndGetSuccessCoursesByTeacher(System.IAsyncResult result) {
            MvcClient.CoursesDbService.DtoSuccess[] retVal = this.EndGetSuccessCoursesByTeacher(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetSuccessCoursesByTeacherCompleted(object state) {
            if ((this.GetSuccessCoursesByTeacherCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetSuccessCoursesByTeacherCompleted(this, new GetSuccessCoursesByTeacherCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetSuccessCoursesByTeacherAsync(string query) {
            this.GetSuccessCoursesByTeacherAsync(query, null);
        }
        
        public void GetSuccessCoursesByTeacherAsync(string query, object userState) {
            if ((this.onBeginGetSuccessCoursesByTeacherDelegate == null)) {
                this.onBeginGetSuccessCoursesByTeacherDelegate = new BeginOperationDelegate(this.OnBeginGetSuccessCoursesByTeacher);
            }
            if ((this.onEndGetSuccessCoursesByTeacherDelegate == null)) {
                this.onEndGetSuccessCoursesByTeacherDelegate = new EndOperationDelegate(this.OnEndGetSuccessCoursesByTeacher);
            }
            if ((this.onGetSuccessCoursesByTeacherCompletedDelegate == null)) {
                this.onGetSuccessCoursesByTeacherCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetSuccessCoursesByTeacherCompleted);
            }
            base.InvokeAsync(this.onBeginGetSuccessCoursesByTeacherDelegate, new object[] {
                        query}, this.onEndGetSuccessCoursesByTeacherDelegate, this.onGetSuccessCoursesByTeacherCompletedDelegate, userState);
        }
        
        public MvcClient.CoursesDbService.DtoSuccess[] GetSuccessCoursesByWeekday(string Weekday) {
            return base.Channel.GetSuccessCoursesByWeekday(Weekday);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginGetSuccessCoursesByWeekday(string Weekday, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetSuccessCoursesByWeekday(Weekday, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public MvcClient.CoursesDbService.DtoSuccess[] EndGetSuccessCoursesByWeekday(System.IAsyncResult result) {
            return base.Channel.EndGetSuccessCoursesByWeekday(result);
        }
        
        private System.IAsyncResult OnBeginGetSuccessCoursesByWeekday(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string Weekday = ((string)(inValues[0]));
            return this.BeginGetSuccessCoursesByWeekday(Weekday, callback, asyncState);
        }
        
        private object[] OnEndGetSuccessCoursesByWeekday(System.IAsyncResult result) {
            MvcClient.CoursesDbService.DtoSuccess[] retVal = this.EndGetSuccessCoursesByWeekday(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetSuccessCoursesByWeekdayCompleted(object state) {
            if ((this.GetSuccessCoursesByWeekdayCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetSuccessCoursesByWeekdayCompleted(this, new GetSuccessCoursesByWeekdayCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetSuccessCoursesByWeekdayAsync(string Weekday) {
            this.GetSuccessCoursesByWeekdayAsync(Weekday, null);
        }
        
        public void GetSuccessCoursesByWeekdayAsync(string Weekday, object userState) {
            if ((this.onBeginGetSuccessCoursesByWeekdayDelegate == null)) {
                this.onBeginGetSuccessCoursesByWeekdayDelegate = new BeginOperationDelegate(this.OnBeginGetSuccessCoursesByWeekday);
            }
            if ((this.onEndGetSuccessCoursesByWeekdayDelegate == null)) {
                this.onEndGetSuccessCoursesByWeekdayDelegate = new EndOperationDelegate(this.OnEndGetSuccessCoursesByWeekday);
            }
            if ((this.onGetSuccessCoursesByWeekdayCompletedDelegate == null)) {
                this.onGetSuccessCoursesByWeekdayCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetSuccessCoursesByWeekdayCompleted);
            }
            base.InvokeAsync(this.onBeginGetSuccessCoursesByWeekdayDelegate, new object[] {
                        Weekday}, this.onEndGetSuccessCoursesByWeekdayDelegate, this.onGetSuccessCoursesByWeekdayCompletedDelegate, userState);
        }
        
        public MvcClient.CoursesDbService.DtoSuccess[] GetSuccessCoursesBySearchDepartment(string query) {
            return base.Channel.GetSuccessCoursesBySearchDepartment(query);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginGetSuccessCoursesBySearchDepartment(string query, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetSuccessCoursesBySearchDepartment(query, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public MvcClient.CoursesDbService.DtoSuccess[] EndGetSuccessCoursesBySearchDepartment(System.IAsyncResult result) {
            return base.Channel.EndGetSuccessCoursesBySearchDepartment(result);
        }
        
        private System.IAsyncResult OnBeginGetSuccessCoursesBySearchDepartment(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string query = ((string)(inValues[0]));
            return this.BeginGetSuccessCoursesBySearchDepartment(query, callback, asyncState);
        }
        
        private object[] OnEndGetSuccessCoursesBySearchDepartment(System.IAsyncResult result) {
            MvcClient.CoursesDbService.DtoSuccess[] retVal = this.EndGetSuccessCoursesBySearchDepartment(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetSuccessCoursesBySearchDepartmentCompleted(object state) {
            if ((this.GetSuccessCoursesBySearchDepartmentCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetSuccessCoursesBySearchDepartmentCompleted(this, new GetSuccessCoursesBySearchDepartmentCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetSuccessCoursesBySearchDepartmentAsync(string query) {
            this.GetSuccessCoursesBySearchDepartmentAsync(query, null);
        }
        
        public void GetSuccessCoursesBySearchDepartmentAsync(string query, object userState) {
            if ((this.onBeginGetSuccessCoursesBySearchDepartmentDelegate == null)) {
                this.onBeginGetSuccessCoursesBySearchDepartmentDelegate = new BeginOperationDelegate(this.OnBeginGetSuccessCoursesBySearchDepartment);
            }
            if ((this.onEndGetSuccessCoursesBySearchDepartmentDelegate == null)) {
                this.onEndGetSuccessCoursesBySearchDepartmentDelegate = new EndOperationDelegate(this.OnEndGetSuccessCoursesBySearchDepartment);
            }
            if ((this.onGetSuccessCoursesBySearchDepartmentCompletedDelegate == null)) {
                this.onGetSuccessCoursesBySearchDepartmentCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetSuccessCoursesBySearchDepartmentCompleted);
            }
            base.InvokeAsync(this.onBeginGetSuccessCoursesBySearchDepartmentDelegate, new object[] {
                        query}, this.onEndGetSuccessCoursesBySearchDepartmentDelegate, this.onGetSuccessCoursesBySearchDepartmentCompletedDelegate, userState);
        }
    }
}
